version: '3'

services:
  web:
    image: 'jekyll/jekyll:4.1.0'
    volumes:
      - '.:/app'
    working_dir: '/app'
    ports:
      - '4000:4000'
      - '35729:35729' # necessary for live reload
    command: 'jekyll serve --livereload'